# eureka服务器端的配置信息
spring:
  application:
#    通过项目名称来查找eureka服务器
    name: spring-cloud-eureka

# 配置admin服务监控
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
#    标示本模块为服务端（server）；不添加则表示为客户端（client）
    registerWithEureka: false
    fetchRegistry: false

#    设置eureka服务端地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/