spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
#      分支
      label: master
      server:
#        托管于github
        git:
#          GitHub的uri需要去除.git,码云等需要保留     需要创建一个配置仓库
#          uri: https://github.com/yukiloh/spring-cloud-config
#          search-paths: respo
          
#          2019年10月26日：将config文件替换至原有项目的仓库下
          uri: https://github.com/yukiloh/spring-cloud-project
#          uri下的路径
          search-paths: /spring-cloud-config/respo
#          git的用户名&密码
          username:
          password:
  # 链路追踪
  zipkin:
    base-url: http://localhost:9411
server:
#  spring cloud config中的默认端口为8888,正常情况无法修改!
#  修改需要通过创建bootstrap.properties,添加server.port=XXXX;bootstrap配置文件会被优先加载
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

foo: test