spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://3.113.65.65:9411
  boot:
    admin:
      client:
        url: http://3.113.65.65:8084

server:
  port: 8769

zuul:
  routes:
#    当访问/a指向ribbon的路径，/b为feign
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-web-admin-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.113.65.65:8761/eureka/
