spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: spring-cloud-web-admin-ribbon
      label: master
      profile: dev
  #      profile: prod


#  application:
#    name: spring-cloud-web-admin-ribbon
##    新增了thymeleaf配置
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#server:
#  port: 8764
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/