spring:
  application:
    name: spring-cloud-web-admin-feign

  # admin服务监控
  boot:
    admin:
      client:
        url: http://localhost:8084

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  # 链路追踪
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
#  开启熔断机制
  hystrix:
    enabled: true