spring:
  application:
    name: spring-cloud-web-admin-feign

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

feign:
#  开启熔断机制
  hystrix:
    enabled: true