spring:
  application:
    name: spring-cloud-web-admin-ribbon


  # admin服务监控
  boot:
    admin:
      client:
        url: http://http://192.168.2.110:8084
#        url: http://192.168.1.90:18084



  #    新增了thymeleaf配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  # 链路追踪
  zipkin:
    base-url: http://http://192.168.2.110:9411
#      url: http://192.168.1.90:19411


server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://http://192.168.2.110:8761/eureka/
#      defaultZone: http://192.168.1.90:18761/eureka/