spring:
  application:
    name: spring-cloud-service-sso

server:
  port: 8773

#mabatis配置
mybatis:
  #  实体类路径
  type-aliases-package: com.test.spring.cloud.common.domain
  mapper-locations: classpath:mapper/*.xml

feign:
  #  开启熔断机制
  hystrix:
    enabled: true

  #  允许bean被复写,暂时搁置
  main:
    allow-bean-definition-overriding: true