# 一些所有服务都会用到的的通用配置
spring:
  application:
    name: spring-cloud-common-service
  zipkin:
    base-url: http://3.113.65.65:9411
  boot:
    admin:
      client:
        url: http://3.113.65.65:8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.113.65.65:8761/eureka/