spring:
  application:
    name: spring-cloud-zipkin
  zipkin:
    base-url: http://3.113.65.65:9411
  boot:
    admin:
      client:
        url: http://3.113.65.65:8084

server:
  port: 9411

#2.10后需要开启下列配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.113.65.65:8761/eureka/
