spring:
  application:
    name: spring-cloud-thymeleaf
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix:  .html
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#  允许bean被复写,暂时搁置
  main:
    allow-bean-definition-overriding=true
