spring:
  application:
    name: spring-cloud-service-sso

  ##  数据库--maria
  datasource:
#    url: jdbc:mariadb://192.168.1.90:3306/service-admin
    url: jdbc:mariadb://3.113.65.65:3306/service-admin
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
#      password: zou9RYdAGW2MKoBY
      password: CVQ39Vyt3mg#B5

# 需要页面模板
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


server:
#  eureka服务器端8761
  port: 8773

#mabatis配置
mybatis:
  #  实体类路径
  type-aliases-package: com.test.spring.cloud.common.domain
  mapper-locations: classpath:mapper/*.xml

feign:
  #  开启熔断机制
  hystrix:
    enabled: true