spring:
  application:
    name: spring-cloud-service-posts
  #  数据库--maria
  datasource:
    #    url: jdbc:mariadb://192.168.1.90:3306/service-admin
    url: jdbc:mariadb://3.113.65.65:3306/service-posts
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      #      password: zou9RYdAGW2MKoBY
      password: CVQ39Vyt3mg#B5
  zipkin:
    base-url: http://3.113.65.65:9411
  boot:
    admin:
      client:
        url: http://3.113.65.65:8084
server:
  port: 8764

# 开启mybatis的二级缓存功能
mybatis:
  configuration:
    cache-enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.113.65.65:8761/eureka/

