spring:
  application:
    name: spring-cloud-web-admin-feign

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  zipkin:
    base-url: http://3.113.65.65:9411
  boot:
    admin:
      client:
        url: http://3.113.65.65:8084

server:
  port: 8765

feign:
#  开启熔断机制
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://3.113.65.65:8761/eureka/