spring:
  application:
    name: spring-cloud-maria-service-admin

##  maria-aws
#  datasource:
#    url: jdbc:mariadb://3.113.65.65:3306/service-admin
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: CVQ39Vyt3mg#B5

#  maria-nas
  datasource:
    url: jdbc:mariadb://192.168.1.90:3306/service-admin
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: zou9RYdAGW2MKoBY
