spring:
  application:
    name: spring-cloud-redis

## redis-aws
#  redis:
#    password: pQxWfm339xbT@#
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#    sentinel:
##      sentinel的master名称,为自定义
#      master: mymaster
##      sentinel的各节点地址&端口
##      nodes: 192.168.2.110:26379, 192.168.2.110:26380, 192.168.2.110:26381
#      nodes: 3.113.65.65:26379, 3.113.65.65:26380, 3.113.65.65:26381

# redis-aws
  redis:
    host: 192.168.1.90
    port: 32768
    password: XqQjF&80gXZANz
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

