spring:
  application:
    name: spring-cloud-web-admin-feign

  # admin服务监控
  boot:
    admin:
      client:
        url: http://http://192.168.2.110:8084
#        url: http://192.168.1.90:18084

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  # 链路追踪
  zipkin:
    base-url: http://http://192.168.2.110:9411
#    base-url: http://192.168.1.90:19411

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://http://192.168.2.110:8761/eureka/
#      defaultZone: http://192.168.1.90:18761/eureka/

feign:
#  开启熔断机制
  hystrix:
    enabled: true