spring:
  application:
    name: spring-cloud-service-sso

  ##  数据库--maria
  datasource:
    url: jdbc:mariadb://192.168.1.90:3306/service-admin
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: zou9RYdAGW2MKoBY

# 需要页面模板
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  # admin服务监控
  boot:
    admin:
      client:
#        因切换至nas端所以注释
#        url: http://localhost:8084
        url: http://192.168.1.90:18084

  # 链路追踪
#  zipkin:
##    base-url: http://localhost:9411
#    base-url: http://192.168.1.90:19411

server:
#  eureka服务器端8761
  port: 8773

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.1.90:18761/eureka/

#mabatis配置
mybatis:
  #  实体类路径
  type-aliases-package: com.test.spring.cloud.common.domain
  mapper-locations: classpath:mapper/*.xml


feign:
  #  开启熔断机制
  hystrix:
    enabled: true