spring:
  application:
    name: hello-spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#2.10开始存在下方配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false